name: artifact upload & dwld, concurrency in workflow

on:
  workflow_dispatch
#  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}   
  cancel-in-progress: true

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Upload dragon.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    needs: test_job_2
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: Read File
        run: cat dragon.txt  
    
        run: sleep 300

      - name: Deploy 
        run: echo Deploying...
